---
- hosts: tomcatServer
  become: yes
  vars:
  - warLocalPath: "{{ warNameFilePath }}"
  - warRemotePath: /opt/apache-tomcat-9.0.16/webapps

  tasks:
  - name: deleting the old SpringApp.war file
    file: path={{ warRemotePath }}/SprintApp/SpringApp.war state=absent

  - name: Download WAR to server
    synchronize: src={{ warLocalPath }} dest={{ warRemotePath }}/SpringApp.war
  
  - name: Clear Old file from the Spring APP folder before deployment
    file: path={{ warRemotePath }}/SprintApp/* state=absent  

  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/SpringApp.war dest=/opt/apache-tomcat-9.0.16/webapps/SprintApp/ copy=no mode=0755 owner=tomcat group=tomcat
    notify:
        - Restart tomcat

  - name: Delete remote war file
    file: path={{ warRemotePath }}/SpringApp.war state=absent

  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
